language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-user .
  - docker tag udagram-user "isdance/udagram-user:v-$TRAVIS_BUILD_NUMBER"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "isdance/udagram-user:v-$TRAVIS_BUILD_NUMBER"
